In [1]:
import open3d as o3d
import numpy as np
from open3d import JVisualizer

INFO - 2022-06-10 13:41:24,066 - utils - NumExpr defaulting to 8 threads.


## initialize pointcloud

In [2]:
filePath = "combined_multiway_registered.ply"

print("Load a ply point cloud, print it, and render it")

pcd = o3d.io.read_point_cloud(filePath)
print(pcd)
print(np.asarray(pcd.points))



Load a ply point cloud, print it, and render it
PointCloud with 763197 points.
[[4.08999822e+05 3.66011002e+06 9.68980257e-01]
 [4.08999822e+05 3.66011002e+06 9.67625234e-01]
 [4.08999823e+05 3.66011002e+06 9.68881995e-01]
 ...
 [4.09000147e+05 3.66010984e+06 1.01390742e+00]
 [4.08999964e+05 3.66010968e+06 1.05247449e+00]
 [4.09000147e+05 3.66010984e+06 1.01358821e+00]]


JVisualizer with 1 geometries

## get the minimum of each dimension

In [3]:
data = np.asarray(pcd.points)
print("finding minimums to move cloud to origin")
# get an array of all min values in each dimension [minX, minY, minZ]
minArr = []
for dim in range(3):
    thisMin = data[0][dim]
    for point in data:
        thisMinCurr = point[dim]
        if thisMinCurr < thisMin:
            thisMin = thisMinCurr
    minArr.append(thisMin)
print(f"minimums [x, y, z]: {minArr}")


finding minimums to move cloud to origin
minimums [x, y, z]: [408999.822248412, 3660109.536540864, 0.9442215240273981]


## shift the pointcloud as close to the origin as possible 
## ie subtract the minimums from each dimension 

In [4]:

# make all values in minArr negative
negMinArr = [-1 * minArr[0], -1 * minArr[1], -1 * minArr[2]]
pcd.translate(negMinArr)
print("shifted by subtracting the minimum vector")
print(np.asarray(pcd.points))


shifted by subtracting the minimum vector
[[6.60758815e-05 4.85440422e-01 2.47587331e-02]
 [1.76724861e-05 4.82059979e-01 2.34037095e-02]
 [1.03367766e-03 4.87154182e-01 2.46604713e-02]
 ...
 [3.24886606e-01 3.03986174e-01 6.96858966e-02]
 [1.41871267e-01 1.42510677e-01 1.08252963e-01]
 [3.24598684e-01 3.01450366e-01 6.93666827e-02]]


In [6]:
# visualize the shifted pointcloud
visualizer = JVisualizer()
visualizer.add_geometry(pcd)
visualizer.show()

JVisualizer with 1 geometries