In [1]:
import open3d as o3d
import numpy as np
from open3d import JVisualizer

INFO - 2022-06-10 14:06:13,289 - utils - NumExpr defaulting to 8 threads.


## initialize pointcloud

In [2]:
filePath = "combined_multiway_registered.ply"

print("Load a ply point cloud, print it, and render it")

pcd = o3d.io.read_point_cloud(filePath)
print(pcd)
print(np.asarray(pcd.points))



Load a ply point cloud, print it, and render it
PointCloud with 763197 points.
[[4.08999822e+05 3.66011002e+06 9.68980257e-01]
 [4.08999822e+05 3.66011002e+06 9.67625234e-01]
 [4.08999823e+05 3.66011002e+06 9.68881995e-01]
 ...
 [4.09000147e+05 3.66010984e+06 1.01390742e+00]
 [4.08999964e+05 3.66010968e+06 1.05247449e+00]
 [4.09000147e+05 3.66010984e+06 1.01358821e+00]]


## set the center to the origin

In [3]:
pcd.translate((0, 0, 0), relative = False)
print(np.asarray(pcd.points))


[[-0.17312368  0.22899821 -0.04636102]
 [-0.17317208  0.22561776 -0.04771604]
 [-0.17215608  0.23071197 -0.04645928]
 ...
 [ 0.15169685  0.04754396 -0.00143385]
 [-0.03131849 -0.11393154  0.03713321]
 [ 0.15140893  0.04500815 -0.00175307]]


## visualize it

In [4]:
# visualize the shifted pointcloud
visualizer = JVisualizer()
visualizer.add_geometry(pcd)
visualizer.show()

JVisualizer with 1 geometries